// pages/index.js

import Head from 'next/head';
import { Inter } from 'next/font/google';
import Header2 from '../components/organisms/Header2';
import Audentification from '../components/organisms/Audentification';
import HomePage from './HomePage';
import Footer from '../components/organisms/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Company Social Events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Head>
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" /> 
    </Head>

      </Head>
      <main>
        <Header2 />
        <HomePage />
        <Footer/>
      </main>
    </>
  );
}
